# Generated by Django 5.0.5 on 2025-05-02 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playlists', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='queuetrack',
            unique_together={('queue', 'track_id')},
        ),
    ]
